### PR TITLE
Upgrade code to modern JS

### PR DESCRIPTION
**Pull request by justafish**
Updates to modern JS standards.

I can't test this at the moment though as I'm unable to get your container started. The README has an incorrect port, but there still seem to be some other issues. Would love to jump on a hangout with you and debug this!

Should the references to Draco be removed?

### CODE REVIEW

**Comment by juampynr** [comment]
Fixed README and renamed draco to demo. I will look into the airbnb linting. Thanks Sally!

**Comment by justafish** [comment]
@juampynr conflicts resolved

**Comment by juampynr** [comment]
@justafish, I feel that I need to play more with the airbnb standard in order to learn it and get it to work in PHPStorm. I don't want to delay the article so I will leave it as it is. However, I will use that style for my next JavaScript project.

Thanks!

**Comment by juampynr** [comment]
Fixed at https://github.com/juampynr/elasticsearch-nodejs/pull/5

**Pull request closed without merging**
